apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: casey
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 50Mi
            cpu: 50Mi
          limits:
            memory: 50Mi