apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-network-policy
  annotations:
    policies.kyverno.io/title: Require NetworkPolicy
    policies.kyverno.io/category: Sample
    policies.kyverno.io/minversion: 1.3.6
    policies.kyverno.io/subject: Deployment, NetworkPolicy
    policies.kyverno.io/description: >-
      NetworkPolicy is used to control Pod-to-Pod communication
      and is a good practice to ensure only authorized Pods can send/receive
      traffic. This policy checks incoming Deployments to ensure
      they have a matching, preexisting NetworkPolicy.
spec:
  validationFailureAction: enforce
  background: false
  rules:
  - name: require-network-policy
    match:
      resources:
        kinds:
        - Deployment
    preconditions:
      any:
      - key: "{{request.operation}}"
        operator: Equals
        value: CREATE
    # context:
    # - name: policies_count
    #   apiCall:
    #     urlPath: "/apis/networking.k8s.io/v1/namespaces/{{request.namespace}}/networkpolicies"
    #     jmesPath: "items[?label_match(spec.podSelector.matchLabels, `{{request.object.spec.template.metadata.labels}}`)] | length(@)"
    context:
    - name: dictionary
      configMap:
        name: some-config-map
        namespace: default
    validate:
      message: "Every Deployment requires a matching NetworkPolicy."
      deny:
        conditions:
        - key: "{{dictionary.data.env}}"
          operator: LessThan
          value: 20