apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92Mi8iOnsidXNlcm5hbWUiOiJ2aXZla3NhaHUyNiIsInBhc3N3b3JkIjoiNGQ4MzcyZjMtYjc1Mi00MjBjLTg5YzMtZjg2ZGIzZDVjZmYxIiwiZW1haWwiOiJzbWFydHZpdmVrc2FodTEyQGdtYWlsLmNvbSIsImF1dGgiOiJkbWwyWld0ellXaDFNalk2TkdRNE16Y3laak10WWpjMU1pMDBNakJqTFRnNVl6TXRaamcyWkdJelpEVmpabVl4In19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: viveksecret
type: kubernetes.io/dockerconfigjson
