apiVersion: v1
kind: Service
metadata:
  name: myapp-pod
  labels:
    color: orange
  namespace: testing
spec:
  selector:
    app: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376