name: restrict-node-selection
policies:
  -  restrict_usergroup_fsgroup_id.yaml
resources:
  -  resource.yaml
results:
  - policy: restrict-node-selection
    rule: restrict-nodeselector
    resource: security-context-demo
    status: fail
  - policy: restrict-node-selection
    rule: restrict-nodename
    resource: security-context-demo
    status: pass
  
  