apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-1
  labels:
    app: myapp-1
spec:
  containers:
  - name: nginx
    image: nginx:latest
    imagePullPolicy: "Always"

---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-2
  labels:
    app: myapp-2
spec:
  containers:
  - name: nginx
    image: nginx:latest