apiVersion: v1
kind: Service
metadata:
  name: my-service-1
  namespace: practice
  labels:
    foo: hhhhhhh
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376