apiVersion: v1
kind: Service
metadata:
  name: my-service-1
  namespace: testing
  labels:
    foo: bar
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376