apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    foo: bar
spec: 
  containers:
  - name: nginx
    image: nginx:1.12

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    foo: bar
spec:
  selector:
    app: MyApp-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376