apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec: 
  containers:
  - name: nginx
    image: nginx
    # resources:
    #   requests:
    #     memory: ""
    #     cpu: ""
    #   limits:
    #     memory: ""