apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    foo: bar
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
spec:
  containers:
  - name: nginx
    image: nginx:latest
  volumes: 
  - emptyDir: {}
  - hostPath:
      path: "local-path"
