apiVersion: v1
kind: Pod
metadata:
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
  labels:
    foo: bar
  name: myapp-pod
spec:
  containers:
  - image: nginx:latest
    name: nginx
  volumes:
  - emptyDir: {}
